refactor: code cleanup (#2)
* refactor: code cleanup

- Remove `lazy_static` dependency.
- Use `PathBuf`s instead of strings where appropriate in CLI args parse.
- Move template outside `src` directory.
- Reuse code in golden test.

* style: modify flag name

* refactor: typed approach

* style(ci): use correct steps and action inputs

* chore: remove makefile

* fix(ci): command line arg

* docs: wording

* fix(ci): use template from dedicated directory

* style: log when finished

* fix(ci): template directory name

* feat: use single template file

* ci: change file status check

* fix(ci): bash regexp

* style: error printing

* ci: cleaner template

* ci: inspect notices file contents

* ci(action): inspect notices file contents

* fix: template should not list the project's own library as a third party

* ci: "eat your own dog food"

* test(action): set up own branch

* fix: change command line arg, align docs

* docs(golden test): align

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,15 +7,19 @@ inputs:
   project-root: # id of input
     description: "The root directory of the project to check"
     required: false
-    default: "."
-  template-path:
-    description: "The path to the template directory to use"
+    default: ${{ github.workspace }}
+  template-file:
+    description: "The path to the template file to use"
     required: true
+  notices-file:
+    description: "The path to the notices file"
+    required: false
+    default: "THIRD_PARTY_NOTICES.md"
+  rust-licenses-noticer-branch:
+    description: "The branch to use for the rust-licenses-noticer tool"
+    required: false
+    default: "main"
 
-# outputs:
-#   random-number:
-#     description: "Random number"
-#     value: ${{ steps.random-number-generator.outputs.random-number }}
 runs:
   using: "composite"
   steps:
@@ -36,13 +40,13 @@ runs:
         --manifest-path ${{ inputs.project-root }}/Cargo.toml
         list -l crate -f json
         )" >> $GITHUB_ENV
-
       shell: bash
 
     - name: Install rust-licenses-noticer
       run: >
         cargo install
         --git https://github.com/newrelic/rust-licenses-noticer.git
+        --branch ${{ inputs.rust-licenses-noticer-branch }}
         --quiet --locked
       shell: bash
 
@@ -50,18 +54,27 @@ runs:
       run: >
         rust-licenses-noticer
         --dependencies "$LICENSES"
-        --output-file "./THIRD_PARTY_NOTICES.md"
-        --template-path "${{ inputs.template-path }}/*"
+        --template-file "${{ inputs.template-file }}"
+        --output-file "${{ inputs.notices-file }}"
       shell: bash
 
-    - name: Check if `THIRD_PARTY_NOTICES.md` was up to date
-      run: >
-        git diff --name-only
-        | grep -q "THIRD_PARTY_NOTICES.md"
-        && { 
-          echo "Third party notices out of date.
-          Please run rust-licenses-noticer in this repo and commit the changes in this PR.";
-          exit 1;
-        }
-        || echo "Third party notices up to date."
+    - name: Check if the notices file was up to date
+      run: |
+        STATUS=$(git status --porcelain --untracked-files=all -- ${{ inputs.notices-file }})
+
+        if [[ "$STATUS" =~ ^"??" ]]; then
+          echo "::error file=${{ inputs.notices-file }},title=untracked-file::Notices file was created. Please run rust-licenses-noticer locally and commit the changes."
+          echo "::group::Notices file contents"
+          git diff -- ${{ inputs.notices-file }}
+          echo "::endgroup::"
+          exit 1
+        elif [[ "$STATUS" =~ ^" M" ]]; then
+          echo "::error file=${{ inputs.notices-file }},title=modified-file::Notices file was modified. Please run rust-licenses-noticer locally and commit the changes."
+          echo "::group::Notices file diff"
+          git diff -- ${{ inputs.notices-file }}
+          echo "::endgroup::"
+          exit 1
+        else
+          echo "Third party notices up to date."
+        fi
       shell: bash
